apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops
  namespace: argocd
spec:
  project: default
  destination:
    namespace: giropops
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      valueFiles: 
      - values.yaml
    repoURL: 'https://github.com/monalizavitor/LINUXtips-giropops-senhas.git'
    targetRevision: feat/cd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true